# Generated by Django 4.2.13 on 2024-05-21 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='make_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vechile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
